name: develop

on:
  push:
    branches:
      - 'develop'

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.RUNNER_GITHUB_TOKEN}} 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: |
            git config --global user.email "bokker11@hotmail.com"
            git config --global user.name "Norbert Takács"
      - run: npm ci
      - run: npm run build
      - run: npm test
      # - run: node node_modules/.bin/release-it --ci --preRelease=alpha
     
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1
      
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
             
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bokker/rss.to.telegram:develop,bokker/rss.to.telegram:${{ steps.package-version.outputs.current-version}}-alpha

  update-stack:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Update deployed stack
        run: |
          curl --fail --insecure --request POST --url ${{ secrets.DEV_HOOK }}